import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <head>
        <title>Basic React page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <header className={styles.header}>
        <navbar className={styles.navbar}>
          <h1>Bailard Foundation</h1>

          <nav className={styles.navList}>
            <a href="#">About</a>
            <a href="#">News</a>
            <a href="#">Read Me</a>
            <a href="#">Take Action</a>
          </nav>
        </navbar>

        <hero className={styles.hero}>
          <h2>Sustainability</h2>
          <h2>Starts With You</h2>
          <a href="#">Learn More</a>
        </hero>
      </header>
      <main className={styles.main}>Hello world</main>
      <footer></footer>
    </div>
  );
}
